### ISSUE TITLE
How to turn the default of "Remeber Password in Keychain" to off?

### ISSUE THREAD

**Issue by manonfgoo** [lukas-zronek/ssh-askpass-mac#2]
Hi,

is there any config option allowing to turn the "Remeber Password in Keychain" by default to  off, meaning that the user must explicitly check the box to save the password in Keychain

**Comment by lukas-zronek** [comment]
Hi,

try the latest release v1.2:

https://github.com/lukas-zronek/ssh-askpass-mac/releases/download/v1.2/ssh-askpass-mac.zip

The last selection of whether to rembember the passphrase in the keychain is retained.
Once you untick "Remember passphrase in my keychain", it will be always disabled.

**Comment by lukas-zronek** [comment]
I'm closing this issue. Please feel free to create a new ticket.
